version: "3.7"
services:
  telepanorama-nginx:
    image: telepanorama-nginx-image:0.0.1
    networks:
      - telepanorama-network
  decorator-nginx:
    image: decorator-nginx-image:0.0.1
    configs:
        - source: decorator-nginx-nginx-conf
          target: /etc/nginx/nginx.conf
        - source: decorator-nginx-default-conf
          target: /etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - telepanorama-network
  decorator-php:
    image: decorator-php-image:0.0.1
    environment:
      SITE_MODE: dev
    volumes:
      - ./decorator/coverage:/var/www/html/coverage # для разработки
    ports:
      - 2201:22
    networks:
      - telepanorama-network
  showcase-nginx:
    image: showcase-nginx-image:0.0.1
    configs:
      - source: showcase-nginx-nginx-conf
        target: /etc/nginx/nginx.conf
      - source: showcase-nginx-default-conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - source: showcase-image-volume
        target: /usr/share/nginx/html/textures
        type: volume
    ports:
      - 80:80
    networks:
      - telepanorama-network
networks:
  telepanorama-network:
volumes:
  showcase-image-volume:
  decorator-coverage-volume:
configs:
  showcase-nginx-nginx-conf:
    file: ./deployment/telepanorama/showcase/nginx/nginx.conf
  showcase-nginx-default-conf:
    file: ./deployment/telepanorama/showcase/nginx/default.conf
  decorator-nginx-nginx-conf:
    file: ./deployment/telepanorama/decorator/nginx/nginx.conf
  decorator-nginx-default-conf:
    file: ./deployment/telepanorama/decorator/nginx/default.conf