export var settings = {
    CAMERA_DISPLACEMENT_RADIUS: 50,
    BACKGROUND_SPHERE_RADIUS: 500,
    MENU_ITEM_SPHERE_RADIUS: 100,
    MENU_ANGLE_BETWEEN_ITEMS: .6,
    CANVAS_CONTAINER_ID: 'canvas-container'
};